# name: Attach debug build

# on: pull_request

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [15.4.0]

#     steps:
#       - uses: actions/checkout@v2
#       - name: set up JDK 1.8
#         uses: actions/setup-java@v1
#         with:
#           java-version: 1.8
#       - name: Install NodeJS ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#       - name: Install yarn
#         run: npm install yarn -g
#       - name: Install dependencies
#         run: yarn
#       - name: Make Gradle executable
#         run: chmod +x ./android/gradlew
#       - name: Build Debug APK
#         run: cd android && ./gradlew assembleDebug
#       - name: Upload Artifact
#         uses: actions/upload-artifact@v2
#         with:
#           name: app-debug.apk
#           path: android/app/build/outputs/apk/debug/
#           if-no-files-found: error
