name: Release to Play store

on:
  pull_request
  # push:
  #   branches:
  #     - master

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.4.0]

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install yarn
        run: npm install yarn -g
      - name: Install dependencies
        run: yarn
      - name: Make Gradle executable
        run: chmod +x ./android/gradlew
      - name: Build Release APK
        run: cd android && ./gradlew assembleRelease

      # - name: Upload Android Release to Play Store
      #   uses: r0adkll/upload-google-play@v1
      #   with:
      #     serviceAccountJson: ${{ SERVICE_ACCOUNT_JSON }}
      #     packageName: com.zenzizenzi.camhelp
      #     releaseFile: ${{ SIGNED_RELEASE_FILE}}
      #     track: production
      #     inAppUpdatePriority: 0
      #     userFraction: 1
      #   whatsNewDirectory: distribution/whatsnew
      #     mappingFile: app/build/outputs/mapping/release/mapping.txt
