name: Cancel stale builds

on:
  push:

jobs:
  cancel:
    name: 'Cancel previous stale builds'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.7.0
        with:
          workflow_id: 4440469,4423802,4441015, # List of workflow ids that we want to cancel https://api.github.com/repos/vannevelj/camhelp/actions/workflows
          access_token: ${{ secrets.GITHUB_TOKEN }}
